### ISSUE TITLE
'include' directive with a remote AsciiDoctor file doesn't work.

### ISSUE THREAD

**Issue by izeye** [asciidoctor/asciidoctor-gradle-plugin#146]
'include' directive with a local AsciiDoctor file works fine,

but with a remote file doesn't work.

With 'asciidoctor' command, it works fine.

Doesn't the AsciiDoctor Gradle plugin support 'include' directive with a remote file yet?

Or am I missing something?

This is the repository which the situation reproduces:

https://github.com/izeye/samples-asciidoc

**Comment by abelsromero** [comment]
In order to include remote files you need to add a special directive `allow-uri-read`. I've seen that in your example you're using the version 1.5.0 of the plugin, to set this option just add the following block to you build.gradle:

```
asciidoctor {
     options = [
        attributes: [
            'allow-uri-read': ''
        ]
    ]
}
```

Note that the syntax for `attributes` changed a bit in later versions of the plugin, there're some examples in the https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/development/README.adoc.

**Comment by izeye** [comment]
@abelsromero Thanks! It works :+1: BTW do you know why the 'allow-uri-read' attribute is not enabled by default not like the command 'asciidoctor'?

**Comment by abelsromero** [comment]
The reason why is not enabled is related to the securty modes and it's basically for security reasons. I'm not an expert, but It seems it is possible to inject some macros in the files and this combined with the option to download remote files open some dangerous options.

The only think I can offer for sure is the reference to the different modes asciidoctor can run http://asciidoctor.org/docs/user-manual/#running-asciidoctor-securely. I hope this offers some light into the matter.

**Comment by izeye** [comment]
@abelsromero Thanks. It helped me guess the reason.

**Comment by aalmiray** [comment]
I suppose this issue can be closed now, is this correct?

**Comment by izeye** [comment]
@aalmiray Yes :-)
