### ISSUE TITLE
Duplicate files in Gradle distributions

### ISSUE THREAD

**Issue by jponge** [asciidoctor/asciidoctor-gradle-plugin#173]
We have a simple `distributions` rule to get the Asciidoctor outputs and wrap them in a distribution:

``` groovy
from(asciidoctor) {
  into 'docs'
}
```

However this yields the outputs twice, as in:

```
$ tree build/install/golo/docs
build/install/golo/docs
├── golo-guide.html
├── golodoc
│   ├── gololang
│   │   ├── Adapters.html
│   │   ├── Async.html
│   │   ├── Decorators.html
│   │   ├── JSON.html
│   │   ├── LazyLists.html
│   │   └── StandardAugmentations.html
│   └── index.html
└── html5
    └── golo-guide.html

3 directories, 9 files
```

The `html5/golo-guide.html` and `golo-guide.html` files are duplicate. The Asciidoctor-specific folder is fine:

```
$ tree build/asciidoc/
build/asciidoc/
└── html5
    └── golo-guide.html

1 directory, 1 file
```

This happens for the `eclipse/golo-lang` project and I suspect for others, too.

**Comment by aalmiray** [comment]
Am I correct in assuming that `golo-guide.html` is created by the `asciidoctor` task only?

**Comment by jponge** [comment]
Yes, see
https://github.com/eclipse/golo-lang/blob/master/build.gradle#L115

**Comment by aalmiray** [comment]
At first glance this appears to be an issue with the `copySpec` used in the distribution block. I can replicate the problem with a simple `Copy` task like the following one:

    task copyDocs(type: Copy) {
        destinationDir = "${buildDir}/mydocs" as File
        from(asciidoctor) {
            into 'docs'
        }
    }

However printing the outputs of the `asciidoctor` task results in

    [/private/tmp/golo-lang/build/asciidoc, /private/tmp/golo-lang/build/asciidoc/html5]

which means the `copySpec` is doing the right thing. The problem arises because of the multiple backend support that the current `AsciidoctorTask` support. The value for `outputDir` is originally set to `$buildDir/asciidoctor`; then the backend specific directories (there may be multiple backends such as `html5` and `pdf` for example) are added.

I'm afraid we don't have a quick fix for this issue just yet. We have filed https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/161 and https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/157 to keep track of the new design.

In the meantime, what you can do is to define a more specific place form where to copy the output adoc files, such as "$buildDir/asciidoctor/html5". I know it's not ideal because anyone may change the configuration of the `asciidoctor` task to point to a different output location, but  that's highly unlikely with good team communication (and a code comment :wink:)

**Comment by jponge** [comment]
@aalmiray how would you do that on our build?

**Comment by aalmiray** [comment]
Here's one way

    from(project.file("$buildDir/asciidoctor/html5")) {
        into 'docs'
    }

**Comment by jponge** [comment]
:+1:
