### ISSUE TITLE
Suggestion: implicitely add asciidoctorj-pdf and asciidoctorj-diagram dependencies

### ISSUE THREAD

**Issue by eshepelyuk** [asciidoctor/asciidoctor-gradle-plugin#187]
Currently, to use PDF conversion or diagram generation, one needs to add dependencies to 
`buildscript.dependencies` section, that is not quite comfortable.

My suggestion is to add those dependencies inside plugin's `apply` method, together with `asciidoctorj`, so end-user will not take care about `AsciidoctorJ` dependency management anymore.

I am ready to provide PR with corresponding tests.

@aalmiray , @mojavelinux what do you think ?

**Comment by aalmiray** [comment]
Sounds good, but what about other extensions such as `asciidoctorj-screenshot`? Other questions I have are:

 - if `pdf` and `diagram` extensions are always brought by `asciidoctor-gradle`, how can you turn them off when you don't want them?
 - `diagram` extension requires additional gems, thus we always pair `asciidoctor-gradle` with `jruby-gradle`. This ljnk should not be hard, so that the feature can be disabled. See above.
 - `diagram` requires additional software to be installed, such as graphviz, plantUML, etc. Autoenabling this extension is half-way the steps needed to successfully use it if other diagram formats are used.

**Comment by mojavelinux** [comment]
> diagram extension requires additional gems, thus we always pair asciidoctor-gradle with jruby-gradle. 

This is no longer true now that asciidoctorj-diagram is available. However, it's true that not all users choose to go that route.

**Comment by mojavelinux** [comment]
> diagram requires additional software to be installed, such as graphviz, plantUML, etc.

PlantUML is provided, but the dot command is not.
