### ISSUE TITLE
png and png.cache file from plantuml all over the place

### ISSUE THREAD

**Issue by schauder** [asciidoctor/asciidoctor-gradle-plugin#199]
I have plantuml diagrams in my documents.

When building the documents I get png files with cryptic names, for example (diag-54ee5477a17725424c0e5c8471d03f39.png) in the src folder where my asciidoc files are and png.cache files in the subfolder .asciidoctor/diagram with similar cryptic names with the same names modulo the .cache suffix

These files never get cleaned (not even with an explicit clean task). Since the names are generated on every run, I get more and more of these files, until I manually remove them.

and I really think they don't belong in the src folder of the asciidoc document, or subfolders there of.

**Comment by mojavelinux** [comment]
Since Asciidoctor Diagram 1.5.0, these cache files are no generated into a dot directory that is relative to the output directory. Which version are you using?

I'd like to see the location of the cache dir be configurable. Either way, that request needs to be addressed in https://github.com/asciidoctor/asciidoctor-diagram.

**Comment by schauder** [comment]
Ah, more versions to upgrade! I'm currently using 1.4.0

**Comment by schauder** [comment]
Upgrading to 1.5.1 fixed the issue.

Thx

**Comment by mojavelinux** [comment]
:+1:
