### ISSUE TITLE
Change HighlightJS location?

### ISSUE THREAD

**Issue by Lucasvo1** [asciidoctor/asciidoctor-gradle-plugin#204]
We are behind a proxy and cannot resolve hljs from the cloudfare CDN. Is it somehow possible to pass in a parameter such as `highlightjsdir 'location'`?

**Comment by abelsromero** [comment]
I don't know if you ask because you already knew, but `highlightjsdir ` is precisely the name of the attribute you need.
The manual contains the details to use a local version of highlightjs located in your project: http://asciidoctor.org/docs/user-manual/#highlight-js. You may be able to use it to point to an url also.

If you want to add the attribute to your documents*, add it to the attributes section in your gradle build: https://github.com/asciidoctor/asciidoctor-gradle-plugin#options--attributes.

* Note the -a in the manual applies if you're are using the ruby shell, so ignore it.

**Comment by Lucasvo1** [comment]
It works. Thanks very much for the help!
